### ISSUE TITLE
Float layout bug with target-counter used in table of contents

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#1053]
This problem occasionally happens when `float: right` is used for positioning page number reference in TOC items.

```css
nav li a::after {
  float: right;
  content: target-counter(attr(href url), page);
}
```

![Screenshot 2022-12-08 at 19 07 03](https://user-images.githubusercontent.com/3324737/206422349-d2ce045c-16b1-43b5-a29c-481364e3b0bd.png)
