### ISSUE TITLE
Inline margins on leader not working properly

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#1114]
Test sample: 

HTML: https://gist.githack.com/MurakamiShinyu/1ce91fe9e822ad1872653b4219fbc999/raw/toc-leader6.html
(GitHub Gist: https://gist.github.com/MurakamiShinyu/1ce91fe9e822ad1872653b4219fbc999 )

Test with Vivliostyle Viewer v2.22.2:
https://vivliostyle.github.io/viewer/v2.22.2/#src=https://gist.githack.com/MurakamiShinyu/1ce91fe9e822ad1872653b4219fbc999/raw/toc-leader6.html

Result screenshot:
![Screenshot 2023-01-28 at 15 16 27](https://user-images.githubusercontent.com/3324737/215250635-491254b3-7787-4869-93ee-433d7aa45917.png)

In this test sample, inline margins are specified on the pseudo element on which `leader()` is specified, as follows:

```css
      nav li a::after {
        content: leader(dotted) " " target-counter(attr(href), page);
        margin-inline-end: -1em;
        margin-inline-start: 0.25em;
      }
```

In the result, the inline margins are not properly applied.
The margin between the item text and the leader is much bigger than the specified margin-inline-start value (0.25em), being affected by the negative margin-inline-end value (-1em).
