### ISSUE TITLE
Leader layout problem dependent on font and language

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#1117]
特定のフォントと言語指定と目次項目テキスト内容によってリーダーのレイアウトの不具合が発生します。

Test sample
HTML: https://gist.githubusercontent.com/MurakamiShinyu/d7c8e693cf9b3ad79dbd97d58f73ce4f/raw/toc-leader8.html
(GitHub Gist: https://gist.github.com/MurakamiShinyu/d7c8e693cf9b3ad79dbd97d58f73ce4f )

Test with Vivliostyle Viewer:
https://vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/d7c8e693cf9b3ad79dbd97d58f73ce4f/raw/toc-leader8.html

Result screenshot:
![Screenshot 2023-01-30 at 14 50 44](https://user-images.githubusercontent.com/3324737/215397660-4ade5b4e-f9e9-471c-bf65-a2470f709a6c.png)

1ページ目の目次ではレイアウト不具合があり、2ページ目の目次では正常にレイアウトされている。違いは、1ページ目は lang="en" で2ページ目は lang="ja" の指定があること。

目次項目のテキストが "1　かな漢字" では問題なし、"2　かな漢字" では問題あり、"2　かな" や "2　漢字" では問題なし、…、などテキスト内容によっても変わるのが不思議。

フォントは "Noto Serif CJK JP" を使用。Variable Fontの TTF TTC版
https://github.com/googlefonts/noto-cjk/blob/main/Serif/Variable/OTC/NotoSerifCJK-VF.ttf.ttc
あるいはOTF TTC版
https://github.com/googlefonts/noto-cjk/blob/main/Serif/Variable/OTC/NotoSerifCJK-VF.otf.ttc
を使用（OSにインストールしてテスト）。

（WebフォントのGoogle Fontsの "Noto Serif JP" も試したが、問題なしだった。）

OSはWindowsとMacでこの問題が起きるのを確認。

ブラウザはGoogle Chromeのリリース版(109.0.5414.119)とCanary版(112.0.5567.0)とで確認。
（SafariとFirefoxでは問題なしだった。）

Vivliostyle CLI v6.2.2 (Chromium 110.0.5481.38)の preview と build でもこの問題を確認。

（`vivliostyle build --render-mode docker` では問題なしだった。OSの違いによるものか、Docker版にインストールされている "Noto Serif CJK JP" フォントのバージョンが違うためかもしれない）

**Comment by MurakamiShinyu** [comment]
同様の問題が起きる別の例

Test sample
HTML: https://gist.githubusercontent.com/MurakamiShinyu/dd000e1a0030e973164a1f126899e82c/raw/alice-toc.html
(GitHub Gist: https://gist.github.com/MurakamiShinyu/dd000e1a0030e973164a1f126899e82c )

Test with Vivliostyle Viewer:
https://vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/dd000e1a0030e973164a1f126899e82c/raw/alice-toc.html

Screenshot:
![Screenshot 2023-03-19 at 23 57 46](https://user-images.githubusercontent.com/3324737/226184459-d324b040-ea76-4cb6-b4af-742c9852d7fa.png)

使用フォント[Google FontsのCrimson Text](https://fonts.google.com/specimen/Crimson+Text)でこの問題が起きている。
GitHubの https://github.com/googlefonts/Crimson/tree/master/fonts/ttf にある CrimonText-Regular.ttf を使った場合も同じ（次のCSSを追加して試せる）。

```css
@font-face {
  font-family: 'Crimson Text';
  src: url('https://raw.githubusercontent.com/googlefonts/Crimson/master/fonts/ttf/CrimsonText-Regular.ttf');
}
```

このサンプルの元の
https://github.com/vivliostyle/vivliostyle_doc/blob/gh-pages/samples/gutenberg/Alice.html
では問題が起きていない。こちらは使用フォントがCrimson Textの古いバージョンだった。
（https://github.com/googlefonts/Crimson/tree/fonts-october2014/Desktop%20Fonts/TTF にある Crimson-Roman.ttf と同じ。次のCSSを追加して試せる）

```css
@font-face {
  font-family: 'Crimson Text';
  src: url('https://raw.githubusercontent.com/googlefonts/Crimson/fonts-october2014/Desktop%20Fonts/TTF/Crimson-Roman.ttf');
}
```


-----

このケースについては原因が判明：
目次項目のテキストが "y" で終わると、リーダー文字の "." とのあいだでペアカーニングが効いて、その文字間が詰まった状態でリーダー文字を増やして伸ばす処理がされる。そのあとでぴったり行末までとどかない分を margin-inline-start によるアキを入れてリーダー文字列の前に入れる。マージンが入るとペアカーニングは効かなくなるので、ペアカーニングで文字間が詰まっていた分がなくなり、アキがその分多く入れられることになって1行に収まらなくなり次の行に送られて、その結果このレイアウト不具合となる。

`font-kerning: none` であればこの不具合は起きない。
