### ISSUE TITLE
image size in page margin boxes

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#1177]
Test case:
https://gist.githubusercontent.com/MurakamiShinyu/28106b91c36d19c2d5ed7dc163748e6f/raw/b41efc7dfe5b644c404c3f4f3194e73a8f3796a8/page-margin-boxes-image.html

```css
@page {
  size: a4;
  margin: 20%;

  @top-left-corner {
    content: url(https://vivliostyle.org/assets/vivliostyle-icon.png);
    border: 1px solid silver;
  }
  @top-left {
    content: url(https://vivliostyle.org/assets/vivliostyle-icon.png);
    border: 1px solid silver;
  }
  @top-center {
    content: url(https://vivliostyle.org/assets/vivliostyle-icon.png);
    border: 1px solid silver;
  }
  @top-right {
    content: url(https://vivliostyle.org/assets/vivliostyle-icon.png);
    border: 1px solid silver;
  }
  @top-right-corner {
    content: url(https://vivliostyle.org/assets/vivliostyle-icon.png);
    border: 1px solid silver;
  }
  @left-top {
    content: url(https://vivliostyle.org/assets/vivliostyle-icon.png);
    border: 1px solid silver;
  }
  @left-middle {
    content: url(https://vivliostyle.org/assets/vivliostyle-icon.png);
    border: 1px solid silver;
  }
  @left-bottom {
    content: url(https://vivliostyle.org/assets/vivliostyle-icon.png);
    border: 1px solid silver;
  }
  @right-top {
    content: url(https://vivliostyle.org/assets/vivliostyle-icon.png);
    border: 1px solid silver;
  }
  @right-middle {
    content: url(https://vivliostyle.org/assets/vivliostyle-icon.png);
    border: 1px solid silver;
  }
  @right-bottom {
    content: url(https://vivliostyle.org/assets/vivliostyle-icon.png);
    border: 1px solid silver;
  }
  @bottom-left-corner {
    content: url(https://vivliostyle.org/assets/vivliostyle-icon.png);
    border: 1px solid silver;
  }
  @bottom-left {
    content: url(https://vivliostyle.org/assets/vivliostyle-icon.png);
    border: 1px solid silver;
  }
  @bottom-center {
    content: url(https://vivliostyle.org/assets/vivliostyle-icon.png);
    border: 1px solid silver;
  }
  @bottom-right {
    content: url(https://vivliostyle.org/assets/vivliostyle-icon.png);
    border: 1px solid silver;
  }
  @bottom-right-corner {
    content: url(https://vivliostyle.org/assets/vivliostyle-icon.png);
    border: 1px solid silver;
  }
}
```

Test with Vivliostyle Viewer (v2.24.3):
https://vivliostyle.github.io/viewer/v2.24.3/#src=https://gist.githubusercontent.com/MurakamiShinyu/28106b91c36d19c2d5ed7dc163748e6f/raw/b41efc7dfe5b644c404c3f4f3194e73a8f3796a8/page-margin-boxes-image.html

Result screenshot:
![screenshot 2023-05-11 17 50 16](https://github.com/vivliostyle/vivliostyle.js/assets/3324737/c83fe91c-a7e8-4f9c-aa55-081ff63b8ee6)

The image vivliostyle-icon.png has 88px x 88px intrinsic size, and width and height properties are not specified, so the image should be displayed with its intrinsic size 88px x 88px. However, in this test result, image width is stretched to the margin-box width in all margin-boxes and image height is stretched to the margin-box height in top- and botttom- margin-boxes.
