### ISSUE TITLE
EPUB Adaptive Layoutを試すとViewerでページが10001ページ生成されてエラーになる

### ISSUE THREAD

**Issue by kght6123** [vivliostyle/vivliostyle.js#1249]
**Describe the bug**
EPUB Adaptive Layoutで試しに柱の配置を試そうとしたらViewerでページが10001ページ生成されて「Error: Too many pages generated (over 10000 pages)」エラーになります。
こちらのページを参考にしました。
https://vivliostyle.github.io/vivliostyle_doc/ja/vivliostyle-user-group-vol1/arinoth/index.html

私の作り方が悪くバグではないかもしれません。解決ができないためお手数をおかけしますが確認させてください🙏

**To Reproduce**
このGitHubのブランチ（ https://github.com/kght6123/mirai-book/tree/epub-adaptive-layout-001/bug/001 ）をcloneまたはexportして、bug/001のディレクトリで、`npx @vivliostyle/cli preview --style ./global.css` を実行すると再現します。

```html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <title>Astro</title>
  </head>
  <body>
    <div class="runninghead">柱</div>
  </body>
</html>
```

```css
html {
  orphans: 1;
  widows: 1;
}
@page {
  size: jis-b5;
}
@-epubx-page-template {
  @-epubx-flow master-single-flow {
    -epubx-flow-consume: all;
  }
  .runninghead {
    -epubx-flow-into: master-running-flow;
    -epubx-flow-options: static exclusive last;
    text-align: right;
  }
  @-epubx-page-master main {
    /* 柱 */
    @-epubx-partition{
      -epubx-enabled: -epubx-expr( page-number % 2==1);
      -epubx-flow-from: master-running-flow;
      position: absolute;
      top: 5mm;
      right: 15mm;
      width: 15mm;
      height: 5mm;
      background-color: 0;
      font-size: 12pt;
      color: #000;
    }
  }
}
```

**Expected behavior**
柱がある空白のページが表示される

**Screenshots**
![スクリーンショット 2024-01-10 23 43 51](https://github.com/vivliostyle/vivliostyle.js/assets/24556516/dadf297c-b829-49e3-bd9b-ee85dc9f7088)

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - CPU: Intel CPU
 - Browser: Chromium Version 120.0.6099.28 (Developer Build) (x86_64)
 - Version: 13.6.3

**Comment by MurakamiShinyu** [comment]
スタイルシートの `@-epubx-page-master main { ... }` に、柱のためのpartitionしかありません。body内容を配置するためのpartitionがないのでこの現象が起きます。HTMLを見ると、bodyの内容は柱に配置される `<div class="runninghead">柱</div>` だけで、それが取り除かれたbodyは空になりますが、その空のブロックが配置されるpartitionは必要です。`@-epubx-page-master main { ... }` に body flow のためのpartition、

```css
    @-epubx-partition {
      -epubx-flow-from: body;
      /* ... */
    }
```

を追加すると解決します。

ただし、それでも問題が起きるケースがあります。次のissue:

- https://github.com/vivliostyle/vivliostyle.js/issues/890

----

Vivliostyleは、EPUB Adaptive Layoutのほかに、CSS Generated Content for Paged Media仕様での柱をつくるしくみ（Named pagesおよびRunning elements）をサポートしています。たぶんEPUB Adaptive Layoutより使いやすいと思います：

- https://drafts.csswg.org/css-gcpm/#running-headers-and-footers
