### ISSUE TITLE
Pictures cannot be paginated

### ISSUE THREAD

**Issue by EnochGao** [vivliostyle/vivliostyle.js#1319]
**Describe the bug**
Pictures cannot be paginated

**To Reproduce**

[bug](https://vivliostyle.org/viewer/#src=data:,%3C!DOCTYPE%20html%3E%20%3Chtml%20lang=%22en%22%3E%20%09%3Chead%3E%20%09%09%3Cmeta%20charset=%22UTF-8%22%20/%3E%20%09%09%3Cmeta%20name=%22viewport%22%20content=%22width=device-width,%20initial-scale=1.0%22%20/%3E%20%09%09%3Ctitle%3Etable%3C/title%3E%20%20%09%09%3Cstyle%3E%20%09%09%09img%20%7B%20%09%09%09%09width:%20500px;%20%09%09%09%09height:%20500px;%20%09%09%09%7D%20%20%09%09%09@page%20%7B%20%09%09%09%09size:%20A4%20portrait;%20%09%09%09%09margin:%2030px;%20%09%09%09%7D%20%20%09%09%09.mate-pro%20%7B%20%09%09%09%09page:%20matePro;%20%09%09%09%7D%20%20%09%09%09.header%20%7B%20%09%09%09%09content:%20element(HeaderRunning);%20%09%09%09%7D%20%09%09%09@page%20matePro%20%7B%20%09%09%09%09@top-center%20%7B%20%09%09%09%09%09content:%20element(HeaderRunning);%20%09%09%09%09%7D%20%09%09%09%7D%20%09%09%3C/style%3E%20%09%3C/head%3E%20%20%09%3Cbody%3E%20%09%09%3Csection%20class=%22mate-pro%22%3E%20%09%09%09%3Cheader%20class=%22header%22%3Eheader%20total%208%20pictures%3C/header%3E%20%09%09%09%3Cimg%20%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09/%3E%20%09%09%09%3Cimg%20%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09/%3E%20%09%09%09%3Cimg%20%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09/%3E%20%09%09%09%3Cimg%20%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09/%3E%20%09%09%09%3Cimg%20%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09/%3E%20%09%09%09%3Cimg%20%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09/%3E%20%09%09%09%3Cimg%20%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09/%3E%20%09%09%09%3Cimg%20%09%09%09%09src=%22https://winkong-frontend.oss-cn-qingdao.aliyuncs.com/images/wk-mhc-ui/logo-ruhai.png%22%20%09%09%09/%3E%20%09%09%3C/section%3E%20%09%3C/body%3E%20%3C/html%3E&f=epubcfi(/2!/4/2/4))
[picture-bug.txt](https://github.com/vivliostyle/vivliostyle.js/files/15245532/picture-bug.txt)

**Comment by MurakamiShinyu** [comment]
@EnochGao Thanks for the bug report! I am investigating the problem.

For now, you can avoid the problem by adding the following style:

```css
img {
  display: block;
}
```

or

```css
body {
  widows: 1;
  orphans: 1;
}
```

It seems that the widows/orphans control is broken when the paragraph consists of inline images only.



By the way, I found a trivial problem in your style:

```css
      .header {
        content: element(HeaderRunning);
      }
      @page matePro {
        @top-center {
          content: element(HeaderRunning);
        }
      }
```

I think this should be:

```css
      .header {
        position: running(HeaderRunning);
      }
      @page matePro {
        @top-center {
          content: element(HeaderRunning);
        }
      }
```
