### ISSUE TITLE
Page float with footnote may cause error "Error: No PageFloatLayoutContext for region"

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#1353]
Test case:
https://gist.githubusercontent.com/MurakamiShinyu/dd49bcd1a882883299bab9d8c256a2c5/raw/test.html

```css
      figure {
        float-reference: page;
        float: block-start;
      }
```

Test with Vivliostyle Viewer v2.30.1:
https://vivliostyle.github.io/viewer/v2.30.1/#src=https://gist.githubusercontent.com/MurakamiShinyu/dd49bcd1a882883299bab9d8c256a2c5/raw/test.html

Screenshot:
![Screenshot 2024-06-28 11 32 38](https://github.com/vivliostyle/vivliostyle.js/assets/3324737/da658597-f1eb-47d0-a650-b8532fc8c902)

**Comment by MurakamiShinyu** [comment]
I found that this error occurs in v2.28.0 and later; it did not occur in v2.27.0 and earlier.

Test with Vivliostyle Viewer v2.27.0:
https://vivliostyle.github.io/viewer/v2.27.0/#src=https://gist.githubusercontent.com/MurakamiShinyu/dd49bcd1a882883299bab9d8c256a2c5/raw/page-float-error.html

![Screenshot 2024-06-22 0 55 50](https://github.com/vivliostyle/vivliostyle.js/assets/3324737/f8170766-16cd-44ca-b0b3-e1631704ac2f)
![Screenshot 2024-06-22 0 55 53](https://github.com/vivliostyle/vivliostyle.js/assets/3324737/0547b972-be44-48dd-a4a1-4a545f074148)

**Comment by MurakamiShinyu** [comment]
This error occurs when footnote is used in page float. e.g.:

```css
    figure {
      float-reference: page;
      float: block-start;
    }

    .footnote {
      float: footnote;
    }
```

```html
  <figure>
    <img
      src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Gustave_Moreau_006.jpg/200px-Gustave_Moreau_006.jpg"
      alt="">
    <figcaption>
      ギュスターヴ・モロー1868年作『プロメテウス』。神話の共通テーマ
      「火」を代表する物語である<span
        class="footnote">世界神話事典 p.129、吉田</span>。</figcaption>
  </figure>
```
