### ISSUE TITLE
CSS parsing throws error

### ISSUE THREAD

**Issue by kwkbtr** [vivliostyle/vivliostyle.js#140]
Parsing following CSS (used in Wikipedia) throws an error:

``` CSS
.alert-container {
    -moz-border-radius: 3px;
    border-radius: 3px;
    background-image:linear-gradient(bottom, rgb(215,215,215) 4%, rgb(230,230,230) 55%, rgb(255,255,255) 100%);
}
```
