### ISSUE TITLE
font-face does not work with a relative path

### ISSUE THREAD

**Issue by mitsuharu** [vivliostyle/vivliostyle.js#1402]
font-faceでフォントファイルを相対的に指定してPDFを作成すると、コンソールに `✖ A network error occurred.` が表示されました。PDFは作成されてますが、指定したフォントは適用されてませんでした。

```css
// 相対パス
@font-face {
    font-family: 'MyFont';
    src: url('MyFont.ttf') format('truetype');
}

// 仮にすべてに適用する
* {
    font-family: 'MyFont', sans-serif;
} 
```

```
% yarn build // ← vivliostyle build を実行しています
✖ A network error occurred.
✔ index.md 技術同人誌テンプレート_title
✔ preface.md はじめに
✔ preface.md はじめに
◡ preface.md はじめに
output/ebook.pdf has been created.
🎉 Built successfully.
```

一方で、フォントファイルを絶対パスで指定する、または別のWebフォントを利用すると、PDFにそのフォントが反映されました。

```css
// 絶対パス
@font-face {
    font-family: 'MyFont';
    src: url('/Users/.../MyFont.ttf') format('truetype');
}

// または Webフォント
@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap');
```

再現環境に関して、フォントデータを入れてzipファイルのサイズが大きくなってしまったので、私の作業リポジトリの再現ブランチを共有します。

https://github.com/mitsuharu/techbook-template/tree/feature/add_local_font_for_issue

フォント指定は `book/theme/fonts.css`、適用したいフォントは同ディレクトリの `./fonts` に格納しています。

https://github.com/mitsuharu/techbook-template/blob/feature/add_local_font_for_issue/book/theme/fonts.css
