### ISSUE TITLE
Support "text-overflow: ellipsis" in page-margin boxes

### ISSUE THREAD

**Issue by yamahige** [vivliostyle/vivliostyle.js#1473]
If possible, I would like to see "text-overflow: ellipsis;" works in page-margin boxes, although `text-overflow` does not appear in the list of [properties that apply to page-margin boxes](https://www.w3.org/TR/css-page-3/#page-property-list)

> The same appendix defines the normative list of CSS 2.1 [[CSS2]](https://www.w3.org/TR/css-page-3/#biblio-css2) [properties that apply to page-margin boxes](https://www.w3.org/TR/css-page-3/#page-property-list). If a conforming user agent supports any of these properties on block boxes, then it must also support that property in the [margin context](https://www.w3.org/TR/css-page-3/#margin-context).
> 
> Other properties defined by [[CSS2]](https://www.w3.org/TR/css-page-3/#biblio-css2) do not apply in these contexts. Behavior for properties not included in CSS 2.1 is undefined.
> 
> Note: The intent of leaving other properties undefined is to allow the gradual addition of appropriate CSS3 properties as they emerge, without having to update this specification with each addition.
https://www.w3.org/TR/css-page-3/#page-properties

https://vivliostyle.org/viewer/#src=https://gist.githubusercontent.com/yamahige/65d758f35bb56bf15975e1a1453d5d00/raw/a0c53b61cda0ff3b023cb2a4fde58bf4c71f1d0a/slide_Text-overflow_ellipsis.html

<img width="655" alt="Image" src="https://github.com/user-attachments/assets/3d746b7c-9b3b-436c-860e-e07a7fcc0794" />

```css
@page {
    @top-left {
        content: "Text-overflow ellipsis in page-margin boxes";
        width: 40%;
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
    }
    @top-center {
        content: "Page " counter(page) " / " counter(pages);
    }
}
```
