### ISSUE TITLE
Support CSS (-webkit-)line-clamp property

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#1489]
MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/line-clamp

```html
<p>
  In this example the <code>-webkit-line-clamp</code> property is set to
  <code>3</code>, which means the text is clamped after three lines. An ellipsis
  will be shown at the point where the text is clamped.
</p>
```

```css
p {
  width: 300px;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
  overflow: hidden;
}
```

This works in all modern browsers, but does not work in Vivliostyle.js that ignores `-webkit-line-clamp` and `-webkit-box-orient` properties.
