### ISSUE TITLE
Page spread inside/outside for CSS margin and float properties

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#1508]
Proposed specs: 
- https://github.com/w3c/csswg-drafts/issues/255
- https://figures.idea.whatwg.org/#floating-inside-and-outside-pages

Example:

```css
figure {
  float: outside;   
  margin-inside: 1ch;
}
```

- `inside` maps to `left` on right-page and `right` on left-page
- `outside` maps to `right` on right-page and `left` on left-page
