### ISSUE TITLE
Page selector parsing issue: `@page: left` (correctly, `@page :left`) should not be allowed

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#1524]
Vivliostyle.js currently accepts the syntax `@page: left` (with a space after the colon) for page selectors, but this is incorrect according to the CSS Paged Media specification. The correct syntax is `@page :left` (with no space after the colon).

Spec: https://drafts.csswg.org/css-page-3/#syntax-page-selector

> ```
> @page = @page <page-selector-list>? { <declaration-rule-list> }
> <page-selector-list> = <page-selector>#
> <page-selector> = [ <ident-token>? <pseudo-page>* ]!
> <pseudo-page> = : [ left | right | first | blank ]
> …
> ```
> 
> - No whitespace is allowed between the productions in `<page-selector>` or `<pseudo-page>` (similar to the rule for `<compound-selector>`).

Good and bad examples:

- ①Good: [page-space-colon.html](https://gist.githack.com/MurakamiShinyu/2ca3e0c717c42fc3b604284dca6ce1d7/raw/page-space-colon.html)
  ```css
  @page :first {
    @top-center {
      content: "First Page";
    }
  }
  @page :left {
    @top-left {
      content: "Left Page";
    }
  }
  @page :right {
    @top-right {
      content: "Right Page";
    }
  }
  ```

- ②Bad (incorrect syntax, but currently accepted by Vivliostyle.js): [page-colon-space.html](https://gist.githack.com/MurakamiShinyu/2ca3e0c717c42fc3b604284dca6ce1d7/raw/page-colon-space.html)
  ```css
  @page: first {
    @top-center {
      content: "First Page";
    }
  }
  @page: left {
    @top-left {
      content: "Left Page";
    }
  }
  @page: right {
    @top-right {
      content: "Right Page";
    }
  }
  ```

**Screenshot in Vivliostyle Viewer:**

①Good and ②Bad (incorrect syntax, but currently accepted by Vivliostyle.js) have the same result.

![Image](https://github.com/user-attachments/assets/c3a71949-73e6-44a9-a818-a11fee7d8304)

**Screenshots in Google Chrome's Print Preview (not using Vivliostyle):**

①Good

![Image](https://github.com/user-attachments/assets/89db2e81-5e03-4b07-a149-3f1252b8bfe1)

②Bad: Page headers are not shown because the page rules have incorrect syntax.

![Image](https://github.com/user-attachments/assets/c50dd63a-d81a-4ab1-8233-652b8c57037c)
