### ISSUE TITLE
An orphan line appears after footnote in vertical writing pages

### ISSUE THREAD

**Issue by mgeorgetw** [vivliostyle/vivliostyle.js#392]
I've been using Vivliostyle Chrome plug-in on a Mac and trying to make a printed book with vertical writing layout. My footnotes are inline spans with simple CSS like:
```css
span.footnote {
  float: footnote;
  counter-increment: footnote;
}
span.footnote::footnote-marker,
span.footnote::footnote-call {
  content: '['counter(footnote)']';
  -webkit-writing-mode: horizontal-tb;
  writing-mode: horizontal-tb;
}
```
However, it seems that footnotes are leaving behind an orphan line on each page (See image below). This only happens with vertical writing layout. Not sure if it's a bug or not.

![vertical_footnote_misplaced](https://user-images.githubusercontent.com/25784056/32890191-b23de39c-cb08-11e7-9fd9-fba3715fb5e7.png)
