### ISSUE TITLE
Not apply counter in the last page of partition

### ISSUE THREAD

**Issue by maxiplay** [vivliostyle/vivliostyle.js#440]
Hello,

I would like generate book like a real french book.  There is no counter on the last page just before a new  chapter.

How can i detect the last page of a partition ?
I though using a thing like this 

`content: -epubx-expr( islastFlowedPage ? counter(page) : none);`

That's the code i'm using 

```
    @-epubx-page-master {
        @-epubx-partition content {

            -epubx-flow-from: body;
            top: {{marginTop}};
            bottom: {{marginBottom}};
            left: -epubx-expr(page-number% 2==1 ? {{marginInterior}}: {{marginExterior}});
            right: -epubx-expr(page-number% 2==0 ? {{marginInterior}}: {{marginExterior}});

        }
            @-epubx-partition class(pagenumber) {
                content: counter(page);
                text-align: center;
                width: {{width}};
                bottom: -epubx-expr({{marginBottom}} - 2em);
            }
      
    }
```

**Comment by MurakamiShinyu** [comment]
Hi,

There is no function such as islastFlowedPage, but it is possible to hide page counter on the blank page just before a new chapter. 
See the following example:

```css
/* To make the blank page if necessary to move the new chapter on the right side: */
section.chapter {
    break-before: right;
}

@-epubx-page-master {
    @-epubx-partition class(pagenumber) {
        /* To hide page counter when the content height is 0 */
        -epubx-enabled: -epubx-expr(content.height > 0);
        content: counter(page);
        text-align: center;
        height: 2em;
        width: {{width}};
        bottom: -epubx-expr({{marginBottom}} - 2em);
    }
    @-epubx-partition content {
        -epubx-flow-from: body;
        top: {{marginTop}};
        /* use margin-bottom instead of 'bottom' to make the height flexible, i.e., 0 if content is empty */
        margin-bottom: {{marginBottom}};
        left: -epubx-expr(page-number% 2==1 ? {{marginInterior}}: {{marginExterior}});
        right: -epubx-expr(page-number% 2==0 ? {{marginInterior}}: {{marginExterior}});
    }
}
```
