### ISSUE TITLE
Support CSS custom properties (variables)

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#540]
CSS Custom Properties for Cascading Variables Module Level 1
https://drafts.csswg.org/css-variables/

**Comment by spring-raining** [comment]
If this feature can be realized, it will be a powerful way to customize Vivliostyle themes. I'm looking forward to the addition of this feature:)

**Comment by depth42** [comment]
I am also voting for this feature. CSS variables are a great way to reduce redundancy in CSS sheets.

**Comment by MurakamiShinyu** [comment]
Now Vivliostyle.js (v2.17.0) supports [CSS Custom Properties for Cascading Variables Module Level 1](https://www.w3.org/TR/css-variables-1/).

CSS variables can be used within any style rules, also can be used in `@page {…}` context. See the following simple example:

```css
:root {
  --page-width: 148mm;
  --page-height: 210mm;
  --page-margin: 20mm;
  --page-header: "My Report";
  --page-footer: counter(page) " / " counter(pages);
}
@page {
  size: var(--page-width) var(--page-height);
  margin: var(--page-margin);
  @top-center {
    content: var(--page-header); 
  }
  @bottom-center {
    content: var(--page-footer); 
  }
}
```
