### ISSUE TITLE
@page z-index

### ISSUE THREAD

**Issue by szk3600** [vivliostyle/vivliostyle.js#668]
The z-index of the page area div is set to 0, and I want to specify this with @page.

Looking at the source, it can be improved by adding "z-index": true, to the props of propertiesAppliedToPartition of css-page.ts.

**Comment by MurakamiShinyu** [comment]
In the current implementation, the `z-index` specified on the `@page { }` context is applied to the page-box.
There is a test sample:
https://github.com/vivliostyle/vivliostyle.js/blob/master/packages/core/test/files/z-index-at-page.html

```css
@page {
  size: 14cm 14cm;
  margin: 2cm;
  z-index: -2;
  background: yellow;
  @top-center {
    content: "Page Header, displayed on all pages";
  }
  @bottom-center {
    content: "Page Footer, displayed on the second and subsequent pages";
    z-index: -1;
  }
}
```

The test result with Vivliostyle Viewer:
https://vivliostyle.org/viewer/#src=https://raw.githack.com/vivliostyle/vivliostyle.js/master/packages/core/test/files/z-index-at-page.html

The result DOM:
```html
...
<div data-vivliostyle-page-box="true" style="position: relative; ...; z-index: -2;">
  <div style="position: absolute; ...; z-index: 0;">
    ...
  </div>
  <div style="position: absolute; ...;">
    <span>Page Header, displayed on all pages</span>
  </div>
  <div style="position: absolute; ...; z-index: -1;">
    <span>Page Footer, displayed on the second and subsequent pages</span>
  </div>
</div>
...
```

Do you think this result is wrong?
Please give us your example that shows the current behavior has problem.
