### ISSUE TITLE
Footnote counter should be predefined and available by default

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#723]
**Describe the bug**

The footnote counter should be predefined and should be incremented for each footnote by default.
(See the spec https://drafts.csswg.org/css-gcpm-3/#footnote-counters)

However, the current footnote implementation in vivliostyle.js, derived from https://github.com/sorotokin/adaptive-layout, requires the author to explicitly define the footnote counter in the stylesheet.

Example stylesheet: (`counter-reset: footnote` and `counter-increment: footnote` are required explicitly)

```css
:root {
  counter-reset: footnote;
}

.footnote {
  float: footnote;
  counter-increment: footnote;
}

.footnote::footnote-call {
  content: counter(footnote);
  vertical-align: super;
  font-size: 80%;
}

.footnote::footnote-marker {
  content: counter(footnote);
  vertical-align: super;
  font-size: 80%;
}
```

Test1: https://gist.githubusercontent.com/MurakamiShinyu/71641c31f78b6459c05d95bc3046f9a3/raw/footnote.html
with Vivliostyle Viewer: https://vivliostyle.org/viewer/#src=https://gist.githubusercontent.com/MurakamiShinyu/71641c31f78b6459c05d95bc3046f9a3/raw/footnote.html

Test2 (without explicit footnote counter reset/increment): https://gist.githubusercontent.com/MurakamiShinyu/71641c31f78b6459c05d95bc3046f9a3/raw/footnote2.html
with Vivliostyle Viewer: https://vivliostyle.org/viewer/#src=https://gist.githubusercontent.com/MurakamiShinyu/71641c31f78b6459c05d95bc3046f9a3/raw/footnote2.html

If `counter-reset: footnote` and `counter-increment: footnote` are removed, the footnote counter is not generated.

**Expected behavior**

The footnote counter should be available even if the `counter-reset: footnote` and `counter-increment: footnote` are not specified in the stylesheet. Therefore, the result of Test2 should be same as Test1.
