### ISSUE TITLE
No break opportunity at block box that has empty content

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#749]
Example:

```html
<div class="test"></div>
<div class="test"></div>
```

```css
.test {
  margin: 10px;
  border: solid 5px gray;
  padding: 200px;
}
```

Gist: https://gist.github.com/MurakamiShinyu/3c98942b9719debb6763e009aaa69d26

Test with Vivliostyle Viewer: https://vivliostyle.vercel.app/#src=https://gist.github.com/MurakamiShinyu/3c98942b9719debb6763e009aaa69d26
