### ISSUE TITLE
CSS parser error, failed to parse stylesheet

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#827]
There are cases where CSS parser errors occur.

Test files and results:
- kf-test-1.html
  - Source (Gist): https://gist.github.com/MurakamiShinyu/4f34afa52ac6e83ffeba2102e3ad72d2#file-kf-test-1-html
    ```css
    @keyframes kf1 {
      from { background-color: white }
      to { background-color: yellow }
    }
    h1 {
      animation: kf1 1s infinite;
      color: red;
      box-shadow:inset 1px 2px 3px rgba(0,0,0,.1);
      color:green;
    }
    ```
    - HTML (GitHack): https://gist.githack.com/MurakamiShinyu/4f34afa52ac6e83ffeba2102e3ad72d2/raw/kf-test-1.html
  - Test with Vivliostyle: https://vivliostyle.vercel.app/#src=https://gist.githack.com/MurakamiShinyu/4f34afa52ac6e83ffeba2102e3ad72d2/raw/kf-test-1.html
    - Result (Error message in the DevTools console log): 
![kf-test-1](https://user-images.githubusercontent.com/3324737/146527492-d07f11f2-bdd9-4c3b-884f-97e718cc8273.png)

      ```
      CSS parser: E_CSS_UNEXPECTED_VAL_END
      Failed to parse stylesheet text: …
      ```
- lg-test-1.html
  - Source (Gist): https://gist.github.com/MurakamiShinyu/4f34afa52ac6e83ffeba2102e3ad72d2#file-lg-test-1-html
    ```css
    h1 {
      background-color: maroon;
      background-image:linear-gradient(45deg, rgba(255, 255, 255, .15)25%, transparent 25%, transparent 50%, rgba(255, 255, 255, .15)50%, rgba(255, 255, 255, .15)75%, transparent 75%, transparent);
      background-size: 40px 40px
    }
    ```
    - HTML (GitHack): https://gist.githack.com/MurakamiShinyu/4f34afa52ac6e83ffeba2102e3ad72d2/raw/lg-test-1.html
  - Test with Vivliostyle: https://vivliostyle.vercel.app/#src=https://gist.githack.com/MurakamiShinyu/4f34afa52ac6e83ffeba2102e3ad72d2/raw/lg-test-1.html
    - Result (Error message in the DevTools console log): 
![lg-test-1](https://user-images.githubusercontent.com/3324737/146527722-d1ed16f6-4df3-4ecb-bf54-c0c330614936.png)

      ```
      E_INVALID_PROPERTY_VALUE background-image
      ```
- lg-test-2.html
  - Source (Gist): https://gist.github.com/MurakamiShinyu/4f34afa52ac6e83ffeba2102e3ad72d2#file-lg-test-2-html
    ```css
    h1 {
      background-image:linear-gradient(45deg, rgba(255, 255, 255, .15)25%, transparent 25%, transparent 50%, rgba(255, 255, 255, .15)50%, rgba(255, 255, 255, .15)75%, transparent 75%, transparent);
      background-size: 40px 40px;
      background-color: maroon;
    }
    ```
    - HTML (GitHack): https://gist.githack.com/MurakamiShinyu/4f34afa52ac6e83ffeba2102e3ad72d2/raw/lg-test-2.html
  - Test with Vivliostyle: https://vivliostyle.vercel.app/#src=https://gist.githack.com/MurakamiShinyu/4f34afa52ac6e83ffeba2102e3ad72d2/raw/lg-test-2.html
    - Result (Error message in the DevTools console log): 
![lg-test-2](https://user-images.githubusercontent.com/3324737/146527761-51256c19-334e-4855-b33a-e5f6ba490281.png)

      ```
      CSS parser: E_CSS_PSEUDOCLASS_SYNTAX
      ```
- lg-test-3.html
  - Source (Gist): https://gist.github.com/MurakamiShinyu/4f34afa52ac6e83ffeba2102e3ad72d2#file-lg-test-3-html
    ```css
    body h1 {
      background-image:linear-gradient(45deg, rgba(255, 255, 255, .15)25%, transparent 25%, transparent 50%, rgba(255, 255, 255, .15)50%, rgba(255, 255, 255, .15)75%, transparent 75%, transparent);
      background-size: 40px 40px;
      background-color: maroon;
    }
    ```
    - HTML (GitHack): https://gist.githack.com/MurakamiShinyu/4f34afa52ac6e83ffeba2102e3ad72d2/raw/lg-test-3.html
  - Test with Vivliostyle: https://vivliostyle.vercel.app/#src=https://gist.githack.com/MurakamiShinyu/4f34afa52ac6e83ffeba2102e3ad72d2/raw/lg-test-3.html
    - Result (Error message in the DevTools console log): 
![lg-test-3](https://user-images.githubusercontent.com/3324737/146527809-19ad6a09-d58e-44dd-9739-98cbe6dae95f.png)

      ```
      CSS parser: E_CSS_MISMATCHED_C_PAR
      ```

Interestingly, when a space is inserted after the colon in these test cases (e.g., correct `background-image:linear-gradient(…)` to `background-image: linear-gradient(…)`), the error does not occur.
