### ISSUE TITLE
Pseudo elements should not be generated when content is none

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vivliostyle.js#832]
Pseudo elements ::before and ::after should have no effects when `content` property value is `none` (or `normal` which is same as `none` on ::before and ::after).

Test sample:
- [pseudo-content-none.html](https://gist.githack.com/MurakamiShinyu/0a55c589c6b83cbf1ef01c0adafdb7ff/raw/pseudo-content-none.html)
  ```css
    p::before {
      border: solid 0.5em red;
      content: none;
    }
    p::after {
      border: solid 0.5em red;
      content: normal;
    }
  ```
  ```html
  <p>Should have no red borders (::before, ::after)</p>
  ```
  - Test with Vivliostyle: https://vivliostyle.vercel.app/#src=https://gist.githack.com/MurakamiShinyu/0a55c589c6b83cbf1ef01c0adafdb7ff/raw/pseudo-content-none.html
  - Result:
![Screen Shot 2022-01-13 at 17 59 53](https://user-images.githubusercontent.com/3324737/149298584-caf591a9-fe10-4fde-ba09-b2666cdb3165.png)
  - Expected behavior: No red borders of the ::before and ::after pseudo-elements appear.
